// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/handlers/gRPC/shortener_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/handlers/gRPC/shortener_service.go -destination=internal/api/handlers/gRPC/mocks/mock_repository.go -package=mocks Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	models "github.com/iubondar/url-shortener/internal/app/models"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckStatus mocks base method.
func (m *MockRepository) CheckStatus(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockRepositoryMockRecorder) CheckStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockRepository)(nil).CheckStatus), ctx)
}

// DeleteByShortURLs mocks base method.
func (m *MockRepository) DeleteByShortURLs(ctx context.Context, userID uuid.UUID, shortURLs []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteByShortURLs", ctx, userID, shortURLs)
}

// DeleteByShortURLs indicates an expected call of DeleteByShortURLs.
func (mr *MockRepositoryMockRecorder) DeleteByShortURLs(ctx, userID, shortURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByShortURLs", reflect.TypeOf((*MockRepository)(nil).DeleteByShortURLs), ctx, userID, shortURLs)
}

// GetStats mocks base method.
func (m *MockRepository) GetStats(ctx context.Context) (models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRepository)(nil).GetStats), ctx)
}

// RetrieveByShortURL mocks base method.
func (m *MockRepository) RetrieveByShortURL(ctx context.Context, shortURL string) (models.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveByShortURL", ctx, shortURL)
	ret0, _ := ret[0].(models.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveByShortURL indicates an expected call of RetrieveByShortURL.
func (mr *MockRepositoryMockRecorder) RetrieveByShortURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveByShortURL", reflect.TypeOf((*MockRepository)(nil).RetrieveByShortURL), ctx, shortURL)
}

// RetrieveUserURLs mocks base method.
func (m *MockRepository) RetrieveUserURLs(ctx context.Context, userID uuid.UUID) ([]models.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveUserURLs", ctx, userID)
	ret0, _ := ret[0].([]models.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveUserURLs indicates an expected call of RetrieveUserURLs.
func (mr *MockRepositoryMockRecorder) RetrieveUserURLs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveUserURLs", reflect.TypeOf((*MockRepository)(nil).RetrieveUserURLs), ctx, userID)
}

// SaveURL mocks base method.
func (m *MockRepository) SaveURL(ctx context.Context, userID uuid.UUID, url string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, userID, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockRepositoryMockRecorder) SaveURL(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockRepository)(nil).SaveURL), ctx, userID, url)
}

// SaveURLs mocks base method.
func (m *MockRepository) SaveURLs(ctx context.Context, urls []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURLs", ctx, urls)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveURLs indicates an expected call of SaveURLs.
func (mr *MockRepositoryMockRecorder) SaveURLs(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURLs", reflect.TypeOf((*MockRepository)(nil).SaveURLs), ctx, urls)
}
