// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/shortener.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateIDHandler_CreateID_FullMethodName = "/shortener.CreateIDHandler/CreateID"
)

// CreateIDHandlerClient is the client API for CreateIDHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateIDHandlerClient interface {
	CreateID(ctx context.Context, in *CreateIDRequest, opts ...grpc.CallOption) (*CreateIDResponse, error)
}

type createIDHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateIDHandlerClient(cc grpc.ClientConnInterface) CreateIDHandlerClient {
	return &createIDHandlerClient{cc}
}

func (c *createIDHandlerClient) CreateID(ctx context.Context, in *CreateIDRequest, opts ...grpc.CallOption) (*CreateIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIDResponse)
	err := c.cc.Invoke(ctx, CreateIDHandler_CreateID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateIDHandlerServer is the server API for CreateIDHandler service.
// All implementations must embed UnimplementedCreateIDHandlerServer
// for forward compatibility.
type CreateIDHandlerServer interface {
	CreateID(context.Context, *CreateIDRequest) (*CreateIDResponse, error)
	mustEmbedUnimplementedCreateIDHandlerServer()
}

// UnimplementedCreateIDHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateIDHandlerServer struct{}

func (UnimplementedCreateIDHandlerServer) CreateID(context.Context, *CreateIDRequest) (*CreateIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateID not implemented")
}
func (UnimplementedCreateIDHandlerServer) mustEmbedUnimplementedCreateIDHandlerServer() {}
func (UnimplementedCreateIDHandlerServer) testEmbeddedByValue()                         {}

// UnsafeCreateIDHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateIDHandlerServer will
// result in compilation errors.
type UnsafeCreateIDHandlerServer interface {
	mustEmbedUnimplementedCreateIDHandlerServer()
}

func RegisterCreateIDHandlerServer(s grpc.ServiceRegistrar, srv CreateIDHandlerServer) {
	// If the following call pancis, it indicates UnimplementedCreateIDHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateIDHandler_ServiceDesc, srv)
}

func _CreateIDHandler_CreateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateIDHandlerServer).CreateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateIDHandler_CreateID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateIDHandlerServer).CreateID(ctx, req.(*CreateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateIDHandler_ServiceDesc is the grpc.ServiceDesc for CreateIDHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateIDHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortener.CreateIDHandler",
	HandlerType: (*CreateIDHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateID",
			Handler:    _CreateIDHandler_CreateID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shortener.proto",
}
